// Regenerates docs/data.js from the three vendored mhgu-editor JSONs.
// Run: node tools/build-data.js
//
// Emits window.MHGU_TALISMAN_DATA = { dataVersion, tiers, trees, names }.
//
// `tiers` is the sparse charm table roll.js expects: four charm kinds, each a map of
// skill-tree id -> [slot1Min, slot1Max, slot2Min, slot2Max]. An all-zero half means the tree
// cannot appear in that slot; an all-zero row means the kind cannot roll it at all.
//
// NOTE ON WHAT IS NOT HERE ANY MORE.
//
// This file used to enumerate every goal the app could ever put on a card and integrate its
// probability in closed form, baking four per-kind numbers into each one. That stopped being
// possible when cards began pruning the tree pool: a card keeps only 20 of the 137 trees, and
// every probability in the app depends on which 20, so there is no fixed catalogue to bake.
// Both the enumeration and the maths now live in docs/goals.js and run at card-generation
// time. Keeping a second copy here would only give them somewhere to drift apart.
//
// The four charm kinds are the ONLY axis the ranges vary on. Talisman rarity (1-10) is a
// separate thing: it is the equip id, fixed when the item is created, and roll.js maps it to
// a kind purely to know which table bounds a given talisman's skills.

const { readFileSync, writeFileSync } = require("node:fs");
const { createHash } = require("node:crypto");
const { join } = require("node:path");

const root = join(__dirname, "..");
const read = (f) => readFileSync(join(root, f), "utf8");

const rawTable = read("talisman_charm_table.json");
const rawSkills = read("skills.json");
const rawNames = read("talisman.json");

const TABLE = JSON.parse(rawTable);   // {kind: [206][4]} dense, index = tree id
const TREES = JSON.parse(rawSkills);  // {id: "Attack"}
const NAMES = JSON.parse(rawNames);   // {rarity: "Pawn Talisman"}

const KIND_ORDER = ["mystery", "shining", "timeworn", "enduring"];

// Densify -> sparse, dropping rows the kind cannot roll at all.
const tiers = {};
for (const t of KIND_ORDER) {
  const out = {};
  TABLE[t].forEach((row, id) => {
    if (id === 0) return;
    if (row[0] === 0 && row[1] === 0 && row[2] === 0 && row[3] === 0) return;
    out[id] = row;
  });
  tiers[t] = out;
}

// Hashes the source bytes, and rides in every seed's fingerprint, so a data rebuild makes old
// seeds warn rather than silently produce a different card.
const dataVersion = createHash("sha256").update(rawTable + rawSkills + rawNames).digest("hex").slice(0, 12);

writeFileSync(
  join(root, "docs", "data.js"),
  "// Auto-generated by tools/build-data.js. Do not edit by hand.\n" +
  "window.MHGU_TALISMAN_DATA = " + JSON.stringify({ dataVersion, tiers, trees: TREES, names: NAMES }) + ";\n"
);

console.log("dataVersion", dataVersion);
for (const t of KIND_ORDER) {
  const rows = Object.keys(tiers[t]).length;
  const s1 = Object.values(tiers[t]).filter((r) => !(r[0] === 0 && r[1] === 0)).length;
  const s2 = Object.values(tiers[t]).filter((r) => !(r[2] === 0 && r[3] === 0)).length;
  console.log("  " + t.padEnd(9), "rows", String(rows).padStart(3), " slot1", String(s1).padStart(3), " slot2", String(s2).padStart(3));
}
console.log("goal enumeration and probabilities now live in docs/goals.js");
